// AUTO-GENERATED by src/scripts/ingestCompanions.ts — do not edit by hand.

export type CompanionManifestEntry = {
  id: string;
  name: string;
  vrmUrl: string;
  /** 3-5 adjectives an 8-year-old can understand, e.g. "super funny", "really patient" */
  personality: string[];
  /** 3 adjectives from the curated personality pool (generated by generateCompanionPersonalities.ts) */
  traits?: string[];
  /** 1-2 sentence description of the companion (generated by generateCompanionPersonalities.ts) */
  bio?: string;
  /** Subject strengths with emoji and 1-5 level (generated by generateCompanionPersonalities.ts) */
  subjects?: Array<{
    label: string;
    emoji: string;
    level: number;
  }>;
};

export const COMPANION_MANIFEST: CompanionManifestEntry[] = [
  {
    "id": "2878599730723533962",
    "name": "2878599730723533962",
    "vrmUrl": "/companions/2878599730723533962.vrm",
    "personality": [
      "friendly",
      "curious",
      "loves learning"
    ]
  },
  {
    "id": "4573661938486170180",
    "name": "4573661938486170180",
    "vrmUrl": "/companions/4573661938486170180.vrm",
    "personality": [
      "friendly",
      "curious",
      "loves learning"
    ]
  },
  {
    "id": "673852811403133503",
    "name": "673852811403133503",
    "vrmUrl": "/companions/673852811403133503.vrm",
    "personality": [
      "friendly",
      "curious",
      "loves learning"
    ]
  },
  {
    "id": "7339187387832391139",
    "name": "7339187387832391139",
    "vrmUrl": "/companions/7339187387832391139.vrm",
    "personality": [
      "friendly",
      "curious",
      "loves learning"
    ]
  },
  {
    "id": "sample",
    "name": "Sample",
    "vrmUrl": "/companions/sample.vrm",
    "personality": [
      "friendly",
      "curious",
      "loves learning"
    ]
  }
];
