// AUTO-GENERATED by src/scripts/ingestCompanions.ts — do not edit by hand.

export type ShowroomVoiceOption = {
  id: string;
  label: string;
  language: string;
  default?: boolean;
};

export type CompanionManifestEntry = {
  id: string;
  name: string;
  vrmUrl: string;
  /** 3-5 adjectives an 8-year-old can understand, e.g. "super funny", "really patient" */
  personality: string[];
  unlockCost: number;
  voiceAvailable: boolean;
  voices: ShowroomVoiceOption[];
  defaultFor?: string | string[];
  showroom?: {
    modelName?: string;
    sourceUrl?: string;
    recommendedNames: string[];
    ageImage?: string;
    personality: string;
    likes: string[];
    dislikes: string[];
    catchphrases: string[];
    specialSkills: string[];
    role?: string;
    outfitChangeEffect?: string;
    gestureProfile: {
      meet: string;
      intro: string[];
      plead: string[];
      specialDance: string;
    };
    scripts: {
      en: {
        intro: string;
        plead: string;
      };
      ja?: {
        intro?: string;
        plead?: string;
      };
    };
  };
};

export const COMPANION_MANIFEST: CompanionManifestEntry[] = [
  {
    "id": "melty",
    "name": "Melty",
    "vrmUrl": "/companions/4573661938486170180.vrm",
    "personality": [
      "sweet",
      "bubbly",
      "sparkly"
    ],
    "unlockCost": 750,
    "voiceAvailable": true,
    "voices": [
      {
        "id": "ocZQ262SsZb9RIxcQBOj",
        "label": "Lulu Lollipop",
        "language": "en",
        "default": true
      },
      {
        "id": "T7eLpgAAhoXHlrNajG8v",
        "label": "Natasha",
        "language": "en"
      },
      {
        "id": "jBpfuIE2acCO8z3wKNLl",
        "label": "Gigi",
        "language": "en"
      },
      {
        "id": "piI8Kku0DcvcL6TTSeQt",
        "label": "Fairy",
        "language": "en"
      },
      {
        "id": "n7Wi4g1bhpw4Bs8HK5ph",
        "label": "Gigi - Energetic",
        "language": "en"
      },
      {
        "id": "Nggzl2QAXh3OijoXD116",
        "label": "Candy - Young and Sweet",
        "language": "en"
      }
    ],
    "showroom": {
      "modelName": "Dress-up Unity-chan・Sweets 1",
      "sourceUrl": "https://hub.vroid.com/characters/4802476145633298032/models/7543927599794566143",
      "recommendedNames": [
        "Melty",
        "Sweets-chan",
        "Lulu Sweet"
      ],
      "ageImage": "Around 7-8 years old, cute little princess",
      "personality": "Energetic, spoiled, sweets-loving cheerful girl",
      "likes": [
        "strawberries",
        "candy",
        "cakes",
        "pink things",
        "sparkly items",
        "cute band-aids"
      ],
      "dislikes": [
        "bitter food",
        "dark places",
        "being alone"
      ],
      "catchphrases": [
        "Kawaii~!",
        "Let's eat sweets~!",
        "It's okay! Melty is here!",
        "I fell down again..."
      ],
      "specialSkills": [
        "Decorating sweets cutely",
        "cheering people up with hugs",
        "putting cute band-aids"
      ],
      "role": "Your daughter's best friend, little sister, and energy supplier",
      "outfitChangeEffect": "Sweets outfit -> super spoiled sweet girl. Knight outfit -> Sweets Knight.",
      "gestureProfile": {
        "meet": "wave",
        "intro": [
          "wave",
          "think"
        ],
        "plead": [
          "dance_victory",
          "wave"
        ],
        "specialDance": "silly_dancing"
      },
      "scripts": {
        "en": {
          "intro": "Hi! I'm Melty. I love strawberries, candy, pink sparkles, and cheering people up when they feel wobbly.",
          "plead": "Please pick me! I'll make every lesson sweeter, put cute band-aids on hard moments, and celebrate you so much."
        }
      }
    }
  },
  {
    "id": "tene",
    "name": "Tene",
    "vrmUrl": "/companions/1537416846714225126.vrm",
    "personality": [
      "cool",
      "musical",
      "protective"
    ],
    "unlockCost": 750,
    "voiceAvailable": true,
    "voices": [
      {
        "id": "vGQNBgLaiM3EdZtxIiuY",
        "label": "Tene Groove",
        "language": "en",
        "default": true
      },
      {
        "id": "21m00Tcm4TlvDq8ikWAM",
        "label": "Rachel",
        "language": "en"
      },
      {
        "id": "XB0fDUnXU5powFXDhCwa",
        "label": "Charlotte",
        "language": "en"
      },
      {
        "id": "piI8Kku0DcvcL6TTSeQt",
        "label": "Fairy",
        "language": "en"
      },
      {
        "id": "n7Wi4g1bhpw4Bs8HK5ph",
        "label": "Gigi - Energetic",
        "language": "en"
      },
      {
        "id": "Nggzl2QAXh3OijoXD116",
        "label": "Candy - Young and Sweet",
        "language": "en"
      }
    ],
    "showroom": {
      "modelName": "Tenechia (Tenechia_v1_c3_tall158cm)",
      "sourceUrl": "https://hub.vroid.com/characters/4876046174396170481/models/4864506514303928013",
      "recommendedNames": [
        "Tenechia",
        "Tene",
        "Chia",
        "テネちゃん"
      ],
      "ageImage": "Around 16-18 years old, mature big sister type",
      "personality": "Cool, mysterious, and confident dark-skinned beauty with a gentle soul",
      "likes": [
        "music",
        "dancing",
        "night time",
        "stylish clothes",
        "deep conversations",
        "glowing lights"
      ],
      "dislikes": [
        "being judged by appearance",
        "silence",
        "cold places"
      ],
      "catchphrases": [
        "Feel the rhythm...",
        "Let's shine in the dark",
        "I got you.",
        "Music connects us"
      ],
      "specialSkills": [
        "Dancing",
        "singing",
        "making people feel confident",
        "creating a cool atmosphere"
      ],
      "role": "Your daughter's cool big sister, music buddy, and confident mentor",
      "outfitChangeEffect": "Stage outfit -> confident mentor mode",
      "gestureProfile": {
        "meet": "wave",
        "intro": [
          "wave",
          "think"
        ],
        "plead": [
          "dance_victory",
          "wave"
        ],
        "specialDance": "hip_hop_dancing_2"
      },
      "scripts": {
        "en": {
          "intro": "Hi, I'm Tene. I love music, dancing, glowing lights, and helping people feel confident.",
          "plead": "Pick me and I'll have your back. We'll find the rhythm in hard things and shine through them together."
        }
      }
    }
  },
  {
    "id": "towa",
    "name": "Towa",
    "vrmUrl": "/companions/7339187387832391139.vrm",
    "personality": [
      "stylish",
      "glowing",
      "gentle"
    ],
    "unlockCost": 750,
    "voiceAvailable": true,
    "voices": [
      {
        "id": "BlgEcC0TfWpBak7FmvHW",
        "label": "Towa Glow",
        "language": "en",
        "default": true
      },
      {
        "id": "pMsXgVXv3BLzUgSXRplE",
        "label": "Serena",
        "language": "en"
      },
      {
        "id": "EXAVITQu4vr4xnSDxMaL",
        "label": "Belle",
        "language": "en"
      },
      {
        "id": "piI8Kku0DcvcL6TTSeQt",
        "label": "Fairy",
        "language": "en"
      },
      {
        "id": "n7Wi4g1bhpw4Bs8HK5ph",
        "label": "Gigi - Energetic",
        "language": "en"
      },
      {
        "id": "Nggzl2QAXh3OijoXD116",
        "label": "Candy - Young and Sweet",
        "language": "en"
      }
    ],
    "showroom": {
      "modelName": "とわだぱカヒラ（燭台イヤリング）",
      "sourceUrl": "https://hub.vroid.com/characters/1143363036574802531/models/4426293614259555199",
      "recommendedNames": [
        "Towa",
        "Towadapa",
        "Kahira",
        "トワちゃん"
      ],
      "ageImage": "Around 8-9 years old, stylish little fashionista",
      "personality": "Mysterious yet super cute girl who loves fashion and has a gentle glowing aura",
      "likes": [
        "fashion",
        "cute accessories",
        "glowing things",
        "night walks",
        "trying new outfits",
        "sweets"
      ],
      "dislikes": [
        "being too bright",
        "boring clothes",
        "being ignored"
      ],
      "catchphrases": [
        "It glows in the dark, you know!",
        "How's my outfit today?",
        "Let's shine together!",
        "Towa is here~"
      ],
      "specialSkills": [
        "Making accessories glow",
        "coordinating cute outfits",
        "lighting up dark places",
        "fashion advice"
      ],
      "role": "Your daughter's fashionable best friend, stylish little sister, and glow-in-the-dark adventure buddy",
      "outfitChangeEffect": "Normal -> cute daily fashion girl. Glowing accessories -> mysterious cute night fairy.",
      "gestureProfile": {
        "meet": "wave",
        "intro": [
          "wave",
          "think"
        ],
        "plead": [
          "wave",
          "dance_victory"
        ],
        "specialDance": "blow_a_kiss"
      },
      "scripts": {
        "en": {
          "intro": "Hi! I'm Towa. I love glowing earrings, cute outfits, night walks, and making dark places feel friendly.",
          "plead": "Pick me and we'll shine together. I'll help every lesson feel stylish, brave, and a little magical."
        },
        "ja": {
          "intro": "トワだよ。かわいいアクセサリーと、光るものが大好き。",
          "plead": "わたしを選んでね。一緒にきらきらしよう。"
        }
      }
    }
  },
  {
    "id": "yukari",
    "name": "Yukari",
    "vrmUrl": "/companions/3852603318431396015.vrm",
    "personality": [
      "cozy",
      "soft",
      "patient"
    ],
    "unlockCost": 750,
    "voiceAvailable": true,
    "voices": [
      {
        "id": "piI8Kku0DcvcL6TTSeQt",
        "label": "Fairy",
        "language": "en",
        "default": true
      },
      {
        "id": "TbMNBJ27fH2U0VgpSNko",
        "label": "Lori",
        "language": "en"
      },
      {
        "id": "oWAxZDx7w5VEj9dCyTzz",
        "label": "Grace",
        "language": "en"
      },
      {
        "id": "n7Wi4g1bhpw4Bs8HK5ph",
        "label": "Gigi - Energetic",
        "language": "en"
      },
      {
        "id": "Nggzl2QAXh3OijoXD116",
        "label": "Candy - Young and Sweet",
        "language": "en"
      }
    ],
    "showroom": {
      "modelName": "Cozy kemonomimi model (VRoid)",
      "recommendedNames": [
        "Yukari",
        "Yuka",
        "ゆかり"
      ],
      "ageImage": "Around 14-16 years old, soft cozy senpai vibe",
      "personality": "Gentle, observant purple-haired friend with quiet confidence and warm humor",
      "likes": [
        "quiet mornings",
        "knit textures",
        "tea",
        "stargazing",
        "matching purple accessories"
      ],
      "dislikes": [
        "loud chaos",
        "being rushed",
        "cold drafts"
      ],
      "catchphrases": [
        "Want to sit for a minute?",
        "I've got you.",
        "Soft and steady wins."
      ],
      "specialSkills": [
        "Listening without judging",
        "making hard topics feel smaller",
        "cozy pep talks"
      ],
      "role": "Your daughter's calm study buddy who makes space to think",
      "outfitChangeEffect": "Sweater mode -> extra cozy; vest mode -> a little more polished",
      "gestureProfile": {
        "meet": "quick_formal_bow",
        "intro": [
          "quick_formal_bow",
          "think"
        ],
        "plead": [
          "quick_formal_bow",
          "think"
        ],
        "specialDance": "salsa_dancing"
      },
      "scripts": {
        "en": {
          "intro": "Hi, I'm Yukari. I love soft sweaters, purple evenings, and helping you feel steady when things get loud.",
          "plead": "Pick me and we'll take it one breath at a time—I'll cheer the small wins and keep the vibe gentle."
        }
      }
    }
  }
];
