import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: [
      "src/tests/test-six-tools.ts",
      "src/tests/test-canvas-latency.ts",
      "src/tests/test-role-separation.ts",
      "src/tests/test-canvas-barge-in-preserve.ts",
      "src/tests/test-load-homework-folder.ts",
      "src/tests/test-worksheet-session-submit.ts",
      "src/tests/test-pending-transcript.ts",
      "src/tests/test-word-builder-feedback.ts",
      "src/tests/test-word-builder-tool-slot.ts",
      "src/tests/test-spelling-homework-gate.ts",
      "src/tests/test-psychologist-context.ts",
      "src/tests/test-today-plan.ts",
      "src/tests/test-session-plan-injection.ts",
      "src/tests/test-audit-log.ts",
      "src/tests/test-web-toolkit-no-logAttempt.ts",
      "src/tests/test-canvas-voice-sync.ts",
      "src/tests/test-session-subject-diag.ts",
      "src/tests/test-plan-session-sm2.ts",
      "src/tests/test-generate-story-image.ts",
      "src/tests/test-karaoke-reading-suppression.ts",
      "src/tests/test-karaoke-matchWord.ts",
      "src/tests/test-karaoke-accuracy.ts",
      "src/tests/test-reading-complete-gap.ts",
      "src/tests/test-compare-branches.ts",
      "src/tests/test-adventure-types.ts",
      "src/tests/test-child-profile.ts",
      "src/tests/test-bandit.ts",
      "src/tests/test-theme-registry.ts",
      "src/tests/test-node-rating-io.ts",
      "src/algorithms/*.test.ts",
      "src/engine/*.test.ts",
    ],
  },
});
