import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    // Engine/integration tests mutate real paths under src/context/<childId>/; parallel files race.
    fileParallelism: false,
    environment: "node",
    include: [
      "src/tests/test-six-tools.ts",
      "src/tests/test-canvas-latency.ts",
      "src/tests/test-role-separation.ts",
      "src/tests/test-canvas-barge-in-preserve.ts",
      "src/tests/test-load-homework-folder.ts",
      "src/tests/test-worksheet-session-submit.ts",
      "src/tests/test-pending-transcript.ts",
      "src/tests/test-word-builder-feedback.ts",
      "src/tests/test-word-builder-tool-slot.ts",
      "src/tests/test-spelling-homework-gate.ts",
      "src/tests/test-psychologist-context.ts",
      "src/tests/test-today-plan.ts",
      "src/tests/test-session-plan-injection.ts",
      "src/tests/test-audit-log.ts",
      "src/tests/test-web-toolkit-no-logAttempt.ts",
      "src/tests/test-canvas-voice-sync.ts",
      "src/tests/test-session-subject-diag.ts",
      "src/tests/test-plan-session-sm2.ts",
      "src/tests/test-game-contracts.ts",
      "src/tests/test-validate-generated-game.ts",
      "src/tests/test-generate-story-image.ts",
      "src/tests/test-karaoke-reading-suppression.ts",
      "src/tests/test-karaoke-matchWord.ts",
      "src/tests/test-number-words.ts",
      "src/tests/test-karaoke-accuracy.ts",
      "src/tests/test-reading-complete-gap.ts",
      "src/tests/test-compare-branches.ts",
      "src/tests/test-adventure-types.ts",
      "src/tests/test-path-curve.ts",
      "src/tests/test-map-path-layout.ts",
      "src/tests/test-child-profile.ts",
      "src/tests/test-companion-types.ts",
      "src/tests/test-companion-avatar.ts",
      "src/tests/test-companion-api-001.ts",
      "src/tests/test-companion-animate-bridge.ts",
      "src/tests/test-companion-api-registry.ts",
      "src/tests/test-companion-validate.ts",
      "src/tests/test-companion-generate-capabilities.ts",
      "src/tests/test-bandit.ts",
      "src/tests/test-theme-registry.ts",
      "src/tests/test-node-rating-io.ts",
      "src/tests/test-designer-agent.ts",
      "src/tests/test-node-selection.ts",
      "src/tests/test-map-coordinator.ts",
      "src/tests/test-map-iframe-companion-forward.ts",
      "src/tests/test-post-node-pipeline.ts",
      "src/tests/test-adventure-metrics.ts",
      "src/tests/test-session-metrics-note.ts",
      "src/tests/test-ui-accent-contract.ts",
      "src/tests/test-ingest-homework.ts",
      "src/tests/test-ingest-tutoring.ts",
      "src/tests/test-plan-session-homework.ts",
      "src/tests/test-node-routing.ts",
      "src/tests/test-audit-2-sm2-words.ts",
      "src/tests/test-audit-3-psychologist.ts",
      "src/tests/test-build-node-list-due-words.ts",
      "src/tests/test-map-diag-due-words.ts",
      "src/tests/test-event-bus.ts",
      "src/tests/test-server-companion-bridge.ts",
      "src/tests/test-reward-engine.ts",
      "src/tests/test-runtime-mode.ts",
      "src/tests/test-diag-grok-spend-gates.ts",
      "src/tests/test-theme-resolve-diag.ts",
      "src/tests/test-game-event-handler.ts",
      "src/tests/test-session-manager-lines.ts",
      "src/tests/test-take-game-screenshot.ts",
      "src/tests/test-homework-cycle.ts",
      "src/tests/test-ingest-scan-result.ts",
      "src/algorithms/*.test.ts",
      "src/engine/*.test.ts",
    ],
  },
});
