import fs from "fs";
import path from "path";

interface AnimationSidecar {
  name: string;
  label: string;
  defaultLoop: boolean;
}

function validateSidecar(raw: unknown, file: string): AnimationSidecar {
  if (!raw || typeof raw !== "object") {
    throw new Error(`ingestAnimations: ${file} is not a JSON object`);
  }
  const r = raw as Record<string, unknown>;
  if (typeof r.name !== "string" || !r.name.trim()) {
    throw new Error(`ingestAnimations: ${file} missing "name" string`);
  }
  if (typeof r.label !== "string" || !r.label.trim()) {
    throw new Error(`ingestAnimations: ${file} missing "label" string`);
  }
  if (typeof r.defaultLoop !== "boolean") {
    throw new Error(`ingestAnimations: ${file} missing "defaultLoop" boolean`);
  }
  return { name: r.name.trim(), label: r.label.trim(), defaultLoop: r.defaultLoop };
}

export function ingestAnimations(animationsDir: string, outputPath: string): void {
  const files = fs.existsSync(animationsDir) ? fs.readdirSync(animationsDir) : [];

  const sidecars: AnimationSidecar[] = [];
  for (const file of files) {
    if (!file.endsWith(".json")) continue;
    const fullPath = path.join(animationsDir, file);
    const raw = JSON.parse(fs.readFileSync(fullPath, "utf8")) as unknown;
    sidecars.push(validateSidecar(raw, file));
  }

  sidecars.sort((a, b) => a.name.localeCompare(b.name));

  const manifestEntries = sidecars
    .map(
      (s) =>
        `  { name: ${JSON.stringify(s.name)}, path: ${JSON.stringify(`/animations/${s.name}.fbx`)}, defaultLoop: ${s.defaultLoop}, label: ${JSON.stringify(s.label)} },`,
    )
    .join("\n");

  const idsEntries = sidecars.map((s) => `  ${JSON.stringify(s.name)},`).join("\n");

  const output = [
    `// AUTO-GENERATED by src/scripts/ingestAnimations.ts — do not edit by hand`,
    `// Run: npm run ingest:animations`,
    ``,
    `export interface AnimationManifestEntry {`,
    `  name: string;`,
    `  path: string;`,
    `  defaultLoop: boolean;`,
    `  label: string;`,
    `}`,
    ``,
    `export const ANIMATION_MANIFEST: readonly AnimationManifestEntry[] = [`,
    sidecars.length > 0 ? manifestEntries : ``,
    `] as const;`,
    ``,
    `export const ANIMATION_IDS = [`,
    sidecars.length > 0 ? idsEntries : ``,
    `] as const;`,
    `export type GeneratedAnimationName = (typeof ANIMATION_IDS)[number];`,
    ``,
  ].join("\n");

  fs.writeFileSync(outputPath, output, "utf8");
}

async function main(): Promise<void> {
  const animationsDir = path.join(process.cwd(), "web/public/animations");
  const outputPath = path.join(
    process.cwd(),
    "src/shared/companions/animations.generated.ts",
  );
  ingestAnimations(animationsDir, outputPath);
  const count = (fs.readFileSync(outputPath, "utf8").match(/name:/g) ?? []).length;
  console.log(`  📋 animations.generated.ts written (${count} entries)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
