import fs from "node:fs";
import path from "node:path";

type CompanionManifestEntry = {
  id: string;
  name: string;
  vrmUrl: string;
  personality: string[];
};

type CompanionSidecar = {
  displayName?: unknown;
  personality?: unknown;
};

const repoRoot = process.cwd();
const companionsDir = path.join(repoRoot, "web", "public", "companions");
const outputPath = path.join(
  repoRoot,
  "web",
  "src",
  "companion",
  "companions.generated.ts",
);
const defaultPersonality = ["friendly", "curious", "loves learning"];

function capitalise(name: string): string {
  return name.length > 0 ? `${name[0].toUpperCase()}${name.slice(1)}` : name;
}

function readSidecar(filePath: string): CompanionSidecar | null {
  if (!fs.existsSync(filePath)) return null;
  const raw = fs.readFileSync(filePath, "utf8");
  return JSON.parse(raw) as CompanionSidecar;
}

function resolvePersonality(value: unknown): string[] {
  if (!Array.isArray(value)) return defaultPersonality;
  const cleaned = value.filter((v): v is string => typeof v === "string" && v.trim().length > 0);
  return cleaned.length > 0 ? cleaned : defaultPersonality;
}

function renderProgress(done: number, total: number): void {
  const width = 10;
  const filled = total === 0 ? 0 : Math.round((done / total) * width);
  const bar = "█".repeat(filled) + "░".repeat(width - filled);
  process.stdout.write(`\rScanning companions... [${bar}] ${done}/${total}`);
}

function renderManifest(entries: CompanionManifestEntry[]): string {
  return `// AUTO-GENERATED by src/scripts/ingestCompanions.ts — do not edit by hand.

export type CompanionManifestEntry = {
  id: string;
  name: string;
  vrmUrl: string;
  /** 3-5 adjectives an 8-year-old can understand, e.g. "super funny", "really patient" */
  personality: string[];
  /** 3 adjectives from the curated personality pool (generated by generateCompanionPersonalities.ts) */
  traits?: string[];
  /** 1-2 sentence description of the companion (generated by generateCompanionPersonalities.ts) */
  bio?: string;
  /** Subject strengths with emoji and 1-5 level (generated by generateCompanionPersonalities.ts) */
  subjects?: Array<{
    label: string;
    emoji: string;
    level: number;
  }>;
};

export const COMPANION_MANIFEST: CompanionManifestEntry[] = ${JSON.stringify(entries, null, 2)};
`;
}

if (!fs.existsSync(companionsDir)) {
  console.error(`Companions directory does not exist: ${companionsDir}`);
  process.exit(1);
}

const vrmFiles = fs
  .readdirSync(companionsDir)
  .filter((file) => file.toLowerCase().endsWith(".vrm"))
  .sort((a, b) => a.localeCompare(b));

renderProgress(0, vrmFiles.length);

const entries: CompanionManifestEntry[] = [];

vrmFiles.forEach((file, index) => {
  const id = path.basename(file, ".vrm");
  const sidecar = readSidecar(path.join(companionsDir, `${id}.json`));
  const displayName =
    typeof sidecar?.displayName === "string" && sidecar.displayName.trim().length > 0
      ? sidecar.displayName.trim()
      : capitalise(id);

  entries.push({
    id,
    name: displayName,
    vrmUrl: `/companions/${file}`,
    personality: resolvePersonality(sidecar?.personality),
  });
  renderProgress(index + 1, vrmFiles.length);
});

process.stdout.write("\n");
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, renderManifest(entries), "utf8");
console.log(`✅ Companion manifest written — ${entries.length} companions found.`);
