import fs from "fs";
import path from "path";
import type { AttemptInput, DifficultySignal } from "../algorithms/types";
import type { LearningProfile, MoodEntry } from "../context/schemas/learningProfile";
import type { RewardTrigger } from "./rewardEngine";
import { readLearningProfile, writeLearningProfile } from "../utils/learningProfileIO";

export interface SessionData {
  childId: string;
  date: string;
  attempts: AttemptInput[];
  difficultySignals: DifficultySignal[];
  bondExchangeCount: number;
  bondTopics: string[];
  bondQuality: "strong" | "moderate" | "weak";
  sessionDuration: number;
  moodStart: string;
  moodEnd: string;
  mode: string;
  wilsonStep: number;
  wordsRegressed: string[];
  rewardsFired: RewardTrigger[];
  correctStreak: number;
  totalCorrect: number;
  totalAttempts: number;
  /** Optional adventure map summary (TASK-017). */
  adventureMetricsMarkdown?: string;
}

export function formatAdventureMetricsBlock(p: {
  nodesCompleted: number;
  totalNodes: number;
  castleReached: boolean;
  avgAccuracyPct: number;
  avgCompletionMin: number;
  likeCount: number;
  dislikeCount: number;
  nullCount: number;
  theme: string;
  mostEngagedNodeType: string;
  leastEngagedNodeType: string;
  banditStateLabel: string;
}): string {
  return [
    `- Nodes completed: ${p.nodesCompleted}/${p.totalNodes}`,
    `- Castle reached: ${p.castleReached ? "yes" : "no"}`,
    `- Avg accuracy: ${p.avgAccuracyPct}%`,
    `- Avg completion time: ${p.avgCompletionMin} min`,
    `- Ratings: ${p.likeCount} likes, ${p.dislikeCount} dislikes, ${p.nullCount} null`,
    `- Theme: ${p.theme}`,
    `- Most engaged node type: ${p.mostEngagedNodeType}`,
    `- Least engaged: ${p.leastEngagedNodeType}`,
    `- Bandit state: ${p.banditStateLabel}`,
  ].join("\n");
}

export function writeSessionNote(childId: string, data: SessionData): void {
  const dir = path.resolve(process.cwd(), "src", "context", childId, "session_notes");
  fs.mkdirSync(dir, { recursive: true });

  const dateStr = data.date.slice(0, 10);
  const filePath = path.resolve(dir, `${dateStr}.md`);

  const accuracy = data.totalAttempts > 0
    ? Math.round((data.totalCorrect / data.totalAttempts) * 100)
    : 0;

  const wordsReviewed = [...new Set(data.attempts.map((a) => a.word))];
  const rewardEvents = data.rewardsFired.map((r) => r.event).join(", ") || "none";
  const regressions = data.wordsRegressed.length > 0 ? data.wordsRegressed.join(", ") : "none";

  const metricsBlock =
    data.adventureMetricsMarkdown &&
    data.adventureMetricsMarkdown.trim().length > 0
      ? `\n## Metrics\n${data.adventureMetricsMarkdown.trim()}\n`
      : "";

  const note = `# Session Note — ${dateStr}

## Session
- Duration: ${data.sessionDuration}m
- Mode: ${data.mode}
- Wilson Step: ${data.wilsonStep}
- Mood: ${data.moodStart} → ${data.moodEnd}
- Bond quality: ${data.bondQuality}

## Performance
- Accuracy: ${accuracy}% (${data.totalCorrect}/${data.totalAttempts})
- Words attempted: ${wordsReviewed.join(", ") || "none"}
- Regressions: ${regressions}
- Difficulty zones: ${[...new Set(data.difficultySignals.map((s) => s.zone))].join(", ") || "optimal"}
- Streak best: ${data.correctStreak}

## Bond Phase
- Exchange count: ${data.bondExchangeCount}
- Topics: ${data.bondTopics.join(", ") || "none observed"}

## Algorithm Data
- SM-2 updates: ${data.totalAttempts} attempts
- Rewards fired: ${rewardEvents}
- Regressions: ${regressions}
${metricsBlock}
## Clinical Observations
(Generated by Psychologist post-session)

## Plan Adjustments
(Generated by Psychologist post-session)
`;

  fs.writeFileSync(filePath, note, "utf-8");
  console.log(`  🎮 [psychologistBridge] wrote session note: ${dateStr}.md`);
}

export function updateLearningProfileFromSession(
  childId: string,
  data: SessionData,
): void {
  const profile = readLearningProfile(childId);
  if (!profile) return;

  const accuracy = data.totalAttempts > 0 ? data.totalCorrect / data.totalAttempts : 0;

  const moodEntry: MoodEntry = {
    date: data.date,
    startMood: data.moodStart as MoodEntry["startMood"],
    endMood: data.moodEnd as MoodEntry["endMood"],
    bondQuality: data.bondQuality,
    sessionAccuracy: accuracy,
    notableSignals: [],
  };

  profile.moodHistory = [...profile.moodHistory.slice(-9), moodEntry];

  const stats = profile.sessionStats;
  stats.totalSessions++;
  stats.lastSessionDate = data.date;
  stats.averageAccuracy =
    (stats.averageAccuracy * (stats.totalSessions - 1) + accuracy) / stats.totalSessions;
  if (data.correctStreak > stats.streakRecord) {
    stats.streakRecord = data.correctStreak;
  }

  if (data.bondTopics.length > 0) {
    for (const topic of data.bondTopics) {
      const key = topic.toLowerCase().trim();
      profile.bondPatterns.topicFrequency[key] =
        (profile.bondPatterns.topicFrequency[key] || 0) + 1;
    }
    profile.bondPatterns.lastBondQuality = data.bondQuality;
  }

  writeLearningProfile(childId, profile);
}
