// AUTO-GENERATED by scripts/generate-game-registry.ts — do not edit

export interface GameDefinition {
  url: string;
  defaultConfig: Record<string, unknown>;
  voiceEnabled: boolean;
}

export const TEACHING_TOOLS: Record<string, GameDefinition> = {
  "bd-reversal": {
    "url": "/games/bd-reversal-game.html",
    "defaultConfig": {
      "pairs": [
        "bd"
      ],
      "probeWords": [
        "bed",
        "dog",
        "big",
        "duck",
        "bird",
        "dab"
      ]
    },
    "voiceEnabled": true
  },
  "coin-counter": {
    "url": "/games/coin-counter.html",
    "defaultConfig": {},
    "voiceEnabled": true
  },
  "spell-check": {
    "url": "/games/spell-check.html",
    "defaultConfig": {},
    "voiceEnabled": true
  },
  "word-builder": {
    "url": "/games/wordd-builder.html",
    "defaultConfig": {},
    "voiceEnabled": true
  }
};

export const REWARD_GAMES: Record<string, GameDefinition> = {
  "space-invaders": {
    "url": "/games/space-invaders.html",
    "defaultConfig": {
      "duration_seconds": 180,
      "level": 1
    },
    "voiceEnabled": true
  }
};
