// AUTO-GENERATED by scripts/generate-game-registry.ts — do not edit

export interface GameDefinition {
  url: string;
  defaultConfig: Record<string, unknown>;
  voiceEnabled: boolean;
}

export const TEACHING_TOOLS: Record<string, GameDefinition> = {
  "bd-reversal": {
    "url": "/games/bd-reversal-game.html",
    "defaultConfig": {
      "pairs": [
        "bd"
      ],
      "probeWords": [
        "bed",
        "dog",
        "big",
        "duck",
        "bird",
        "dab"
      ]
    },
    "voiceEnabled": true
  },
  "chimp-quest-generated": {
    "url": "/games/chimp-quest-generated.html",
    "defaultConfig": {},
    "voiceEnabled": true
  },
  "clock-game": {
    "url": "/games/clock-game.html",
    "defaultConfig": {
      "hour": 3,
      "minute": 0
    },
    "voiceEnabled": true
  },
  "coin-counter": {
    "url": "/games/coin-counter.html",
    "defaultConfig": {},
    "voiceEnabled": true
  },
  "pronunciation-game": {
    "url": "/games/pronunciation-game.html",
    "defaultConfig": {},
    "voiceEnabled": true
  },
  "spell-check": {
    "url": "/games/spell-check.html",
    "defaultConfig": {},
    "voiceEnabled": true
  },
  "store-game": {
    "url": "/games/store-game.html",
    "defaultConfig": {
      "itemPool": []
    },
    "voiceEnabled": true
  },
  "vault-cracker": {
    "url": "/games/vault-cracker.html",
    "defaultConfig": {},
    "voiceEnabled": true
  },
  "word-builder": {
    "url": "/games/wordd-builder.html",
    "defaultConfig": {},
    "voiceEnabled": true
  }
};

export const REWARD_GAMES: Record<string, GameDefinition> = {
  "asteroid": {
    "url": "/games/asteroid.html",
    "defaultConfig": {
      "duration_seconds": 180,
      "level": 1
    },
    "voiceEnabled": true
  },
  "space-frogger": {
    "url": "/games/space-frogger.html",
    "defaultConfig": {
      "duration_seconds": 180,
      "level": 1
    },
    "voiceEnabled": true
  },
  "space-invaders": {
    "url": "/games/space-invaders.html",
    "defaultConfig": {
      "duration_seconds": 180,
      "level": 1
    },
    "voiceEnabled": true
  }
};
