export const LETTER_ALIASES: Record<string, string[]> = {
  a: ["a", "ay"],
  b: ["b", "bee", "be"],
  c: ["c", "see", "sea"],
  d: ["d", "dee"],
  e: ["e", "ee"],
  f: ["f", "ef", "eff"],
  g: ["g", "gee"],
  h: ["h", "aitch", "hache"],
  i: ["i", "eye"],
  j: ["j", "jay"],
  k: ["k", "kay"],
  l: ["l", "el", "ell"],
  m: ["m", "em"],
  n: ["n", "en"],
  o: ["o", "oh"],
  p: ["p", "pea", "pee"],
  q: ["q", "cue", "queue"],
  r: ["r", "are", "ar"],
  s: ["s", "ess"],
  t: ["t", "tee", "tea"],
  u: ["u", "you", "yew"],
  v: ["v", "vee"],
  w: ["w", "doubleyou", "double-u", "double"],
  x: ["x", "ex"],
  y: ["y", "why", "wye"],
  z: ["z", "zee", "zed"],
};
