/**
 * Writes src/shared/gameRegistry.generated.ts from filesystem discovery.
 * Run automatically via `npm run build` (root).
 */
import fs from "fs";
import path from "path";
import { discoverGames } from "../src/server/games/registryDiscover";

const OUT = path.join(process.cwd(), "src/shared/gameRegistry.generated.ts");

function main(): void {
  const { tools, rewards } = discoverGames();

  const header = `// AUTO-GENERATED by scripts/generate-game-registry.ts — do not edit

export interface GameDefinition {
  url: string;
  defaultConfig: Record<string, unknown>;
  voiceEnabled: boolean;
}

`;

  const toolsJson = JSON.stringify(tools, null, 2) as string;
  const rewardsJson = JSON.stringify(rewards, null, 2) as string;

  const body = `export const TEACHING_TOOLS: Record<string, GameDefinition> = ${toolsJson};

export const REWARD_GAMES: Record<string, GameDefinition> = ${rewardsJson};
`;

  const content = header + body;
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, content, "utf-8");
  console.log("  📋 gameRegistry.generated.ts written");
}

main();
