// AUTO-GENERATED by src/scripts/ingestAnimations.ts — do not edit by hand
// Run: npm run ingest:animations

export interface AnimationManifestEntry {
  name: string;
  path: string;
  defaultLoop: boolean;
  label: string;
}

export const ANIMATION_MANIFEST: readonly AnimationManifestEntry[] = [
  { name: "dance_victory", path: "/animations/dance_victory.fbx", defaultLoop: false, label: "Dance Victory" },
  { name: "idle", path: "/animations/idle.fbx", defaultLoop: true, label: "Idle" },
  { name: "shrug", path: "/animations/shrug.fbx", defaultLoop: false, label: "Shrug" },
  { name: "think", path: "/animations/think.fbx", defaultLoop: false, label: "Think" },
  { name: "wave", path: "/animations/wave.fbx", defaultLoop: false, label: "Wave" },
] as const;

export const ANIMATION_IDS = [
  "dance_victory",
  "idle",
  "shrug",
  "think",
  "wave",
] as const;
export type GeneratedAnimationName = (typeof ANIMATION_IDS)[number];
